const attackMap = {
    2: "Jab 1",
    3: "Jab 2",
    4: "Jab 3",
    5: "Rapid Jabs",
    6: "Dash Attack",
    7: "FTilt",
    8: "UTilt",
    9: "DTilt",
    10: "FSmash",
    11: "USmash",
    12: "DSmash",
    13: "Nair",
    14: "Fair",
    15: "Bair",
    16: "Uair",
    17: "Dair",
    18: "Neutral Special",
    19: "Side Special",
    20: "Up Special",
    21: "Down Special",
    50: "Get Up Attack (Back)",
    51: "Get Up Attack (Front)",
    52: "Pummel",
    53: "FThrow",
    54: "BThrow",
    55: "UThrow",
    56: "DThrow",
    57: "Cargo FThrow",
    58: "Cargo BThrow",
    59: "Cargo UThrow",
    60: "Cargo DThrow",
    61: "Ledge Get Up Attack 100%+",
    62: "Ledge Get Up Attack",
    63: "Beam Sword Jab",
    64: "Beam Sword Tilt Swing",
    65: "Beam Sword Smash Swing",
    66: "Beam Sword Dash Swing",
};

const characterMap = {
    0 : "Cpt. Falcon",
    1 : "Donkey Kong",
    2 : "Fox",
    3 : "Mr. Game & Watch",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Luigi",
    8 : "Mario",
    9 : "Marth",
    10: "Mewtwo",
    11: "Ness",
    12: "Peach",
    13: "Pikachu",
    14: "Ice Climbers (Nana)",
    15: "Jigglypuff",
    16: "Samus",
    17: "Yoshi",
    18: "Sheik",
    19: "Sheik",
    20: "Falco",
    21: "Young Link",
    22: "Dr. Mario",
    23: "Roy",
    24: "Pichu",
    25: "Ganondorf",
    26: "Master Hand",
    27: "Male Wireframe",
    28: "Female Wireframe",
    29: "Giga Bowser",
    30: "Crazy Hand",
    31: "Sandbag",
    32: "Ice Climbers (Popo)",
}

const stageMap  = {
    2: "Fountain of Dreams",
    3: "Pokémon Stadium",
    8: "Yoshi's Story",
    28: "Dream Land N64",
    31: "Battlefield",
    32: "Final Destination"
}

const stageIdxMap = {
    2: 3,
    3: 4,
    8: 5,
    28: 1,
    31: 0,
    32: 2
}

export {
    attackMap,
    characterMap,
    stageMap,
    stageIdxMap
}
